name: Go Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: go build ./go-app/src/apiserver.go
     - run: go test ./go-app/src/apiserver.go
  
  dockerize:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: docker build -t benpinter88/apiserver-image:latest .
     
  deploy:
    needs: [build, dockerize]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_PASSWORD }}" --password-stdin
     - run: docker push benpinter88/apiserver-image:latest
